#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: simple-app
---
# ServiceAccount for Vault authentication
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: simple-app
automountServiceAccountToken: true
---
# ClusterRole for Vault authentication
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: simple-app
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
# ClusterRoleBinding to allow the ServiceAccount to use TokenReview
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: simple-app