# secret
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
  namespace: simple-app
spec:
  type: kv-v2
  mount: creds
  path: app/demo-secret
  destination:
    name: kv-secrets
    create: true
  refreshAfter: 2s
  vaultAuthRef: default
  rolloutRestartTargets:
    - kind: Deployment
      name: static-secrets
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-secrets
  namespace: simple-app
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: static-secrets
  template:
    metadata:
      labels:
        app: static-secrets
    spec:
      containers:
        - name: static-secrets
          image: drum0r/demo-go-web:v1.1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8080
          env:
            - name: TITLE
              value: "Vault Secrets Operator is amazing!"
            - name: SUB_TITLE
              value: "You can now manage your static secrets in Kubernetes using Vault."
            - name: LEARN_LINK
              value: "https://developer.hashicorp.com/vault/docs/platform/k8s/vso"
            - name: FIRST_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: kv-secrets
                  key: message
            - name: IMAGE_URL
              valueFrom:
                secretKeyRef:
                  name: kv-secrets
                  key: image_url
---
# service to expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: static-secrets
  namespace: simple-app
spec:
  type: LoadBalancer
  selector:
    app: static-secrets
  ports:
    - port: 80
      targetPort: 8080
